#+STARTUP: indent

* Hi there 👋
My name is Andrew Soutar. During the day, I write code for @HostiFi, a
Unifi and UISP cloud host. At night, I write more code - mostly in
Common Lisp and C (odd combination, I know), but also Python, JS, C++,
whatever. Most of that code is public. Contributions and comments are
welcome - and if you're having trouble using my code, feel free to
reach out!
* What I'm Working On
- [[https://github.com/andrewsoutar/figment][figment]] :: I'm building a text editor that works the way I do. It's
  written in Common Lisp (to make it easy for me to extend), and uses
  Vulkan for rendering, on top of the raw X11 and Wayland
  protocols. I'm using this as a learning project, to develop a better
  understanding of modern graphics architectures and things like
  that. I have a half-dozen or so other repositories that support this
  project as well.
- [[https://github.com/andrewsoutar/pair.sh][pair.sh]] :: I'm building a lightweight remote-shell tool - think SSH,
  but without having to install packages, set up servers, generate
  keys, open ports, etc. It's designed around the use-case of quick,
  one-off remote access - useful for troubleshooting a problem, pair
  programming, things like that. This one has been on the back burner
  for awhile, so I haven't made significant progress on it.
* More about me
Check out my resume: [[https://andrewsoutar.com/resume]]. (It's
[[https://github.com/andrewsoutar/resume][open-source]], and built with [[https://svelte.dev/][Svelte]]!) Or get in touch:
[[mailto:andrew@andrewsoutar.com][andrew@andrewsoutar.com]].
